### ISSUE TITLE
two comments on inline code

### ISSUE THREAD

**Issue by ousia** [mattgraham/midnight#8]
@mattgraham, many thanks for your Midnight theme.

I use it for <http://www.typehuman.tk/>. Everything is perfect, except two typographical issues with inline code.

I think there are some relevant issues to improve readability:

* x-height for code slightly smaller than for the rest of the text.

* Adding margins and padding for inline code makes more difficult to use it in sentences.

    Allow me this question: would you do the same for emphasis or strong emphasis?

I know I can fork and make a copy with those issues improved. But I”m telling them to you, because I cannot upload my copy as a template to _GitHub Pages_ :smile:.

Many thanks for your help.

**Comment by mattgraham** [comment]
@ousia thanks for the feedback; I've tweaked it a bit and re-pushed to this repo however, I can't promise I can get it into the gh-pages themes as quick. 

Thanks for your feedback and enjoy the theme.
